<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>gce.electronics relay board</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px"><a href="http://www.gce-electronics.com"><img src="/gce.jpg" border="0" /></a> </div>




<div id="title"><div class="right">Relay Board Web Server</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/index.htm">Home</a>

<a href="/preset.htm">Preset</a>
<a href="/ipreset.htm">iPreset</a>

<a href="/protect/timers.htm">Timers</a>
<a href="/dyndns">Dynamic DNS</a>


<a href="/mpfsupload">Firmware Update</a>


<a href="/protect/port.htm">HTTP Port</a>
<a href="/protect/config.htm">Configuration</a>
</div>