<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>Pannel de control :: IPX800 Pro</title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
	<link href="/mchp.css" rel="stylesheet" type="text/css" />
	<script src="/mchp.js" type="text/javascript"></script>
</head>

<body>
	<div id="page">
		<div id="header">
			<h1 id="title">
				Pannel de commande :: IPX800 Pro
			</h1>
	
			<div id="menu">
				<a href="/index.htm">Accueil</a>
				<a href="/ipreset.htm">Mobile</a>
				<a href="/protect/timers.htm">Timers</a>
				<a href="/preset.htm">Préselections</a>
				<a href="/dyndns">Dynamic DNS</a>
				<a href="/mpfsupload">Mise à jour</a>
				<a href="/protect/port.htm">HTTP Port</a>
				<a href="/protect/config.htm">Configuration</a>
			</div>
		</div>